frenchportal/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from learnfrench import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^', include('learnfrench.urls')),
]

learnfrench/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from learnfrench import views

urlpatterns = [
    
    url(r'^$', views.index, name='index'),
    url(r'^news/add/$', views.NewsCreate.as_view(), name="news-add"),
    url(r'^news/(?P<slug>[-\w\d]+)/update/$', views.NewsUpdate.as_view(), name='news-update'), 
    url(r'^news/(?P<slug>[-\w\d]+)/delete/$', views.NewsDelete.as_view(), name='news-delete'), 
    url(r'^news/(?P<slug>[-\w\d]+)/$', view=views.news_article, name='article'), 
    url(r'^news/$', views.NewsListView.as_view(), name="news"),

    url(r'^resource/add/$', views.ResourceCreate.as_view(), name="resource-add"),
    url(r'^resource/(?P<pk>\d+)/update/$', views.ResourceUpdate.as_view(), name="resource-update"),
    url(r'^resource/(?P<pk>\d+)/delete/$', views.ResourceDelete.as_view(), name="resource-delete"),
    url(r'^resource/$', views.ResourceListView.as_view(), name="resource"),

    url(r'^learn/phonology/(?P<quizid>\d+)/(?P<exid>\d+)/training/(?P<pairid>\d+)/$', view=views.training_item, name='training_item'),
    url(r'^learn/phonology/(?P<quizid>\d+)/(?P<exid>\d+)/training/$', view=views.training, name='training'),
    url(r'^learn/phonology/(?P<quizid>\d+)/(?P<exid>\d+)/exercise/(?P<pairid>\d+)/$', view=views.exercise_item, name='exercise_item'),
    url(r'^learn/phonology/(?P<quizid>\d+)/$', view=views.quiz_item, name='quiz'),

    url(r'^learn/syntaxquiz/(?P<quizid>\d+)/$', view=views.syntaxquiz_item, name='syntaxquiz'),
    url(r'^learn/syntaxquiz/(?P<quizid>\d+)/exercise/(?P<exid>\d+)$', view=views.syntaxexer_item, name='syntaxexer'),
    
    url(r'^learn/$', views.learn, name="learn"),
    url(r'^about/', views.about, name="about"),

    url(r'^manage/$', views.ManageView.as_view(), name='manage'),
    url(r'^manage/phonologyquiz/$', views.PhonologyQuizListView.as_view(), name='manage-phonologyquiz'),
    url(r'^manage/phonologyquiz/create/$', views.phonologyquiz_create, name='phonoquiz-create'),
    url(r'^manage/phonologyquiz/(?P<pk>\d+)/update/$', views.phonologyquiz_update, name='phonoquiz-update'),
    url(r'^manage/phonologyquiz/(?P<pk>\d+)/delete/$', views.phonologyquiz_delete, name='phonoquiz-delete'),
    url(r'^manage/phonologyquiz/(?P<pk>\d+)/exercise/create/$', views.phonologyexer_create, name='phonoexer-create'),
    url(r'^manage/phonologyquiz/(?P<pk>\d+)/exercise/list/$', views.phonologyexer_list, name='phonoexer-list'),
    url(r'^manage/phonologyquiz/exercise/(?P<expk>\d+)/edit/$', views.phonologyexer_edit, name='phonoexer-edit'),
    url(r'^manage/phonologyquiz/exercise/(?P<expk>\d+)/delete/$', views.phonologyexer_delete, name='phonoexer-delete'),
    url(r'^manage/phonologyquiz/exercise/(?P<expk>\d+)/wordpair/create/$', views.phonologyexerwordpair_create, name='phonoexer-wordpair-create'),
    url(r'^manage/phonologyquiz/exercise/wordpair/(?P<pairpk>\d+)/delete/$', views.phonologyexerwordpair_delete, name='phonoexer-wordpair-delete'),
    url(r'^manage/phonologyquiz/exercise/(?P<expk>\d+)/word/create/$', views.phonologyword_create, name='phonoword-create'),
    url(r'^manage/phonologyquiz/exercise/(?P<expk>\d+)/word/(?P<wordpk>\d+)/edit/$', views.phonologyword_edit, name='phonoword-edit'),
    
    url(r'^manage/syntaxquiz/$', views.SyntaxQuizListView.as_view(), name='manage-syntaxquiz'),
    url(r'^manage/syntaxquiz/create$', views.SyntaxQuizCreateView.as_view(), name='syntaxquiz-create'),
    url(r'^manage/syntaxquiz/(?P<pk>\d+)/update$', views.SyntaxQuizUpdateView.as_view(), name='syntaxquiz-update'),
    url(r'^manage/syntaxquiz/(?P<pk>\d+)/delete$', views.SyntaxQuizDeleteView.as_view(), name='syntaxquiz-delete'),
    url(r'^manage/syntaxquiz/(?P<pk>\d+)/exercise/create/$', views.syntaxexer_create, name='syntaxexer-create'),
    url(r'^manage/syntaxquiz/(?P<pk>\d+)/exercise/list/$', views.syntaxexer_list, name='syntaxexer-list'),
    url(r'^manage/syntaxquiz/(?P<pk>\d+)/exercise/(?P<expk>\d+)/edit/$', views.syntaxexer_edit, name='syntaxexer-edit'),
    url(r'^manage/syntaxquiz/(?P<pk>\d+)/exercise/(?P<expk>\d+)/delete/$', views.syntaxexer_delete, name='syntaxexer-delete'),
    url(r'^manage/syntaxquiz/(?P<pk>\d+)/exercise/(?P<expk>\d+)/question/create/$', views.syntaxques_create, name='syntaxques-create'),
    url(r'^manage/syntaxquiz/(?P<pk>\d+)/exercise/(?P<expk>\d+)/question/(?P<qupk>\d+)/edit/$', views.syntaxques_edit, name='syntaxques-edit'),
    url(r'^manage/syntaxquiz/(?P<pk>\d+)/exercise/(?P<expk>\d+)/question/(?P<qupk>\d+)/delete/$', views.syntaxques_delete, name='syntaxques-delete'),

]

#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    url(r'^accounts/', include('django.contrib.auth.urls')),
]

learnfrench/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone

from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField 
#from learnfrench.views import news_article


class Resource(models.Model):
    name = models.CharField(max_length=200)
    url = models.URLField()
    description = RichTextField()

    def __str__(self):
        return self.name


class News(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True, allow_unicode=True)
    content = RichTextUploadingField()
    post_date = models.DateField(default=timezone.now())
    image = models.ImageField(upload_to='image/news', null=True, blank=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('article', args=[self.slug])

    class Meta:
        verbose_name_plural = 'News'
        ordering = ['-post_date']


########## Models for Phonology training exercises ############

class PhonologyQuiz(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('quiz', args=[str(self.id)])

    def get_admin_url(self):
        return reverse('phonologyquiz-update', args=[str(self.id)])

    class Meta:
        verbose_name_plural = "Phonology quizzes"

class PhonologyExercise(models.Model):
    quiz = models.ForeignKey(PhonologyQuiz, blank=True, null=True)
    LEVEL_CHOICES = (
        ('In', 'Initiales'),
        ('Me', 'Médianes'),
        ('Fi', 'Finales'),
    )
    title = models.CharField(max_length=200)
    level = models.CharField(max_length=2, choices=LEVEL_CHOICES, default='In')

    class Meta:
        ordering = ['title']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('training', args=[str(self.quiz.id), str(self.id)])

class PhonologyFrenchWordPair(models.Model):
    word1 = models.ForeignKey('PhonologyFrenchWord', related_name='word1')
    word2 = models.ForeignKey('PhonologyFrenchWord', related_name='word2')
    exercise = models.ForeignKey(PhonologyExercise)
    order = models.IntegerField()

    def __str__(self):
        return self.word1.word + ' / ' + self.word2.word

    def get_next_pair(self):
        return PhonologyFrenchWordPair.objects.filter(exercise=self.exercise, order=self.order+1)

    def get_absolute_url(self):
        return reverse('training_item', args=[str(self.exercise.quiz.id), 
            str(self.exercise.id), str(self.id)])

    def get_next_ex_absolute_url(self):
        return reverse('exercise_item', args=[str(self.exercise.quiz.id), 
            str(self.exercise.id), str(self.id)])        

class PhonologyFrenchWord(models.Model):
    word = models.CharField(max_length=200)
    sound_file_mp3 = models.FileField(null=True, blank=True, upload_to='sound/learnfrench')
    sound_file_ogg = models.FileField(null=True, blank=True, upload_to='sound/learnfrench')
    image_file = models.FileField(null=True, blank=True, upload_to='image/learnfrench')

    def __str__(self):
        return self.word


########### Models for Syntax training exercises #############3

class SyntaxQuiz(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('syntaxquiz', args=[str(self.id)])

    class Meta:
        verbose_name_plural = "Syntax quizzes"


class SyntaxExercise(models.Model):
    name = models.CharField(max_length=200)
    quiz = models.ForeignKey(SyntaxQuiz, blank=True, null=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('syntaxexer', quizid=quiz.id, exid=self.id)

    class Meta:
        ordering = ['name']

class SyntaxQuestion(models.Model):
    text = models.TextField()
    exercise = models.ForeignKey(SyntaxExercise)

    def __str__(self):
        return self.text


"""
class SyntaxOptionSet(models.Model):
    question = models.ForeignKey(SyntaxQuestion, on_delete=models.SET_NULL, null=True)
    order = models.IntegerField()

    def __str__(self):
        return "{" + str(self.order) + "}"

class SyntaxOption(models.Model):
    option_set = models.ForeignKey(SyntaxOptionSet, on_delete=models.SET_NULL, null=True)
    choice_text = models.CharField(max_length=200)
    correct = models.BooleanField()
    feedback = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.choice_text

    # need to add validation code. only one correct answer for each question

"""
########### General Question Models ##############
"""
class Question(models.Model):
    exercise = models.ForeignKey(Exercise, on_delete=models.SET_NULL, null=True)
    question_text = models.CharField(max_length=200, blank=True, null=True)
    audiofile = models.URLField(null=True, blank=True)

    def __str__(self):
        return self.question_text

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.SET_NULL, null=True)
    choice_text = models.CharField(max_length=200)

    def __str__(self):
        return self.choice_text
"""

learnfrench/forms.py
from django import forms
from .models import (PhonologyQuiz, PhonologyExercise, PhonologyFrenchWordPair, 
        PhonologyFrenchWord, SyntaxExercise, SyntaxQuestion)


class PhonologyQuizForm(forms.ModelForm):
    class Meta:
        model = PhonologyQuiz
        fields = '__all__'

class PhonologyExerciseModelForm(forms.ModelForm):
    class Meta:
        model = PhonologyExercise
        fields = ('title', 'level',)

"""
class PhonologyFrenchWordPairForm(forms.ModelForm):
    class Meta:
        model = PhonologyFrenchWordPair
        fields = '__all__'
"""

class PhonologyExerciseForm(forms.Form):
    title = forms.CharField(max_length=200)
    level = forms.ChoiceField(choices=PhonologyExercise.LEVEL_CHOICES)

class PhonologyFrenchWordPairForm(forms.ModelForm):
    class Meta:
        model = PhonologyFrenchWordPair
        fields = ('word1', 'word2')


class PhonologyFrenchWordForm(forms.ModelForm):
    class Meta:
        model = PhonologyFrenchWord
        fields = '__all__'

class SyntaxExerciseForm(forms.ModelForm):
    class Meta:
        model = SyntaxExercise
        fields = ('name',)

class SyntaxQuestionForm(forms.ModelForm):
    class Meta:
        model = SyntaxQuestion
        fields = ('text',)

"""
class PhonologyFrenchWordPairForm(forms.Form):
    word1 = forms.CharField(max_length=200)
    word1_image = forms.ImageField()
    word1_sound_file_mp3 = forms.FileField()
    word1_sound_file_ogg = forms.FileField()
    word2 = forms.CharField(max_length=200)
    word2_image = forms.ImageField()
    word2_sound_file_mp3 = forms.FileField()
    word2_sound_file_ogg = forms.FileField()
"""
"""
class PhonologyExerciseAddPairForm(forms.Form):
    word1 = forms.CharField(max_length=200)
    word2 = forms.CharField(max_length=200)
"""
    

learnfrench/templates/learnfrench/teacherportal/includes/partial_phonoexer_list.html
  {% for exer in exer_list %}
    <tr>
      <td>{{ exer.id }}</td>
      <td>{{ exer.title }}</td>
      <td>
        <table class="table table-sm table-responsive">
        {% for word in exer.phonologyfrenchwordpair_set.all %}
        <tr>
          <td>
            <div class="container">
              <div class="row">
                  {% if word.word1.image_file %}
                <div class="col">
                <img class="card-img-top word-card-image" src="/static/{{ word.word1.image_file }}" alt="">
                </div>
                {% endif %}
              <div class="col">
                <h4 class="card-title">{{ word.word1.word }}</h4>
                {% if word.word1.sound_file_mp3 and word.word1.sound_file_ogg %}
                <audio controls>
                <source src="/static/{{ word.word1.sound_file_mp3 }}" type="audio/mp3">
                <source src="/static/{{ word.word1.sound_file_ogg }}" type="audio/ogg">
                <p>Your browser doesn't support HTML5 audio. Here is a <a href="/static/{{ word.word1.sound_file_mp3 }}">link to the audio</a> instead.</p>
                </audio>
                {% endif %}
              </div>
              </div>
              <div class="row">
                <div class="col">
                  <a href="{% url 'phonoword-edit' exer.id word.word1.id %}">Edit word</a>
                </div>
              </div>
            </div>
          </td>
                
          <td>
             <div class="container">
               <div class="row">
                 {% if word.word2.image_file %}
                 <div class="col">
              <img class="card-img-top word-card-image" src="/static/{{ word.word2.image_file }}" alt="">
                 </div>
                 {% endif %}
                 <div class="col">
                <h4 class="card-title">{{ word.word2.word }}</h4>
                {% if word.word2.sound_file_mp3 and word.word2.sound_file_ogg %}
                <audio controls>
                <source src="/static/{{ word.word2.sound_file_mp3 }}" type="audio/mp3">
                <source src="/static/{{ word.word2.sound_file_ogg }}" type="audio/ogg">
                <p>Your browser doesn't support HTML5 audio. Here is a <a href="/static/{{ word.word2.sound_file_mp3 }}">link to the audio</a> instead.</p>
                </audio>
                {% endif %}
                 </div>
               </div>
               <div class="row">
                 <div class="col">
                   <a href="{% url 'phonoword-edit' exer.id word.word2.id %}">Edit word</a>
                 </div>
               </div>
             </div>

          </td>
          <td>
            <a href="{% url 'phonoexer-wordpair-delete' word.id %}">Delete pair</a>
          </td>
        </tr>
        {% endfor %}

        </table>
      </td>
        <td>
          <a class="btn btn-primary btn-sm btn-manage" href="{% url 'phonoexer-wordpair-create' exer.id %}">Add word pair</a>
        <a class="btn btn-info btn-sm btn-manage" href="{% url 'phonoexer-edit' exer.id %}">Edit exercise</a>
        <a class="btn btn-danger btn-sm btn-manage" href="{% url 'phonoexer-delete' exer.id %}">Delete exercise</a>
        <!--button type="button"
                class="btn btn-warning btn-sm js-update-phono-quiz"
                data-url="{% url 'phonoquiz-update' quiz.id %}">
          Edit
        </button>
        &nbsp;
        <button type="button"
                class="btn btn-info btn-sm js-update-phono-exer"
                data-url="{% url 'phonoexer-list' quiz.id %}">
          Edit exercise
        </button>
        &nbsp;
        <button type="button"
                class="btn btn-danger btn-sm js-delete-phono-quiz"
                data-url="{% url 'phonoquiz-delete' quiz.id %}">
          Delete
        </button-->
      </td>
    </tr> 
    {% empty %}
    <tr>
      <td colspan="4" class="text-center bg-warning">No exercise</td>
    </tr>
    {% endfor %}

learnfrench/templates/learnfrench/teacherportal/includes/partial_phonoquiz_create.html
{% load widget_tweaks %}

<form method="post" action="{% url 'phonoquiz-create' %}" class="js-phonoquiz-create-form">
  {% csrf_token %}
  <div class="modal-header">
    <h4 class="modal-title">Create phonology quiz</h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span>&times;</span>
    </button>
  </div>
  <div class="modal-body">
    {% include 'learnfrench/teacherportal/includes/partial_phonoquiz_form.html' %}
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-primary">Create quiz</button>
  </div>
</form>
    

learnfrench/templates/learnfrench/teacherportal/includes/partial_phonoquiz_delete.html
<form method='post' action="{% url 'phonoquiz-delete' quiz.id %}" class="js-phonoquiz-delete-form">
  {% csrf_token %}
  <div class="modal-header">
    <h4 class="modal-title">Delete quiz</h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <div class="modal-body">
    <p class="lead">Are you sure you want to delete quiz: <strong>{{quiz.name}}</strong>?</p>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-primary">Delete quiz</button>
  </div>
</form>

learnfrench/templates/learnfrench/teacherportal/includes/partial_phonoquiz_form.html
{% load widget_tweaks %}

    {% for field in form %}
    <div class="form-group">
      <label for="{{ field.id_for_label }}">{{ field.label_tag}}</label>
      {{ field|add_class:"form-control"|add_error_class:"is-invalid"  }}
      {% for error in field.errors %}
      <div class="feedback">{{ error }}</div>
      {% endfor %}
    </div>
    {% endfor %}

learnfrench/templates/learnfrench/teacherportal/includes/partial_phonoquiz_formset.html
{% load widget_tweaks %}

{{ form.management_form }}
{% for f in form %}
    {% for field in f %}
    <div class="form-group">
      <label for="{{ field.id_for_label }}">{{ field.label_tag}}</label>
      {{ field|add_class:"form-control"|add_error_class:"is-invalid"  }}
      {% for error in field.errors %}
      <div class="feedback">{{ error }}</div>
      {% endfor %}
    </div>
    {% endfor %}
{% endfor %}

learnfrench/templates/learnfrench/teacherportal/includes/partial_phonoquiz_list.html
  {% for quiz in phonologyquiz_list %}
    <tr>
      <td>{{ quiz.id }}</td>
      <td>{{ quiz.name }}</td>
      <td>
        <ul class="list-unstyled">
        {% for ex in quiz.phonologyexercise_set.all %}
        <li>{{ ex.title }}&nbsp; </li>
        {% endfor %}
        </ul>
      </td>
      <td>{{ quiz.description }}</td>
      <td>
        <button type="button"
                class="btn btn-warning btn-sm js-update-phono-quiz"
                data-url="{% url 'phonoquiz-update' quiz.id %}">
          Edit
        </button>
        &nbsp;
        {% if quiz.phonologyexercise_set.all %}
        <a role="button"
                class="btn btn-info btn-sm js-update-phono-exer"
                href="{% url 'phonoexer-list' quiz.id %}">
          Edit exercise
        </a>
        {% else %}
        <a role="button"
           class="btn btn-info btn-sm"
           href="{% url 'phonoexer-create' quiz.id %}">
          Add exercise
        </a>
        {% endif %}
               &nbsp;
        <button type="button"
                class="btn btn-danger btn-sm js-delete-phono-quiz"
                data-url="{% url 'phonoquiz-delete' quiz.id %}">
          Delete
        </button>
      </td>
    </tr> 
    {% empty %}
    <tr>
      <td colspan="4" class="text-center bg-warning">No quiz</td>
    </tr>
    {% endfor %}

learnfrench/templates/learnfrench/teacherportal/includes/partial_phonoquiz_update.html
{% load widget_tweaks %}

<form method="post" action="{% url 'phonoquiz-update' form.instance.pk %}" class="js-phonoquiz-update-form">
  {% csrf_token %}
  <div class="modal-header">
    <h4 class="modal-title">Update phonology quiz</h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span>&times;</span>
    </button>
  </div>
  <div class="modal-body">
    {% include 'learnfrench/teacherportal/includes/partial_phonoquiz_form.html' %}
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-primary">Update quiz</button>
  </div>
</form>
    

learnfrench/templates/learnfrench/teacherportal/includes/partial_syntaxexer_list.html
  {% for exer in exer_list %}
    <tr>
      <td>{{ exer.id }}</td>
      <td>{{ exer.name }}</td>
      <td>
        <ol>
        {% for q in exer.syntaxquestion_set.all %}
        <li>{{ q.text }}
          <p><a href="{% url 'syntaxques-edit' quiz.id exer.id q.id %}">Edit question</a>&nbsp;&nbsp;<a href="{% url 'syntaxques-delete' quiz.id exer.id q.id %}">Delete question</a></p> 
        </li>
        {% endfor %}
        </ol>

      </td>
        <td>
          <a class="btn btn-primary btn-sm btn-manage" href="{% url 'syntaxques-create' quiz.id exer.id %}">Add question</a>
        <a class="btn btn-info btn-sm btn-manage" href="{% url 'syntaxexer-edit' quiz.id exer.id %}">Edit exercise</a>
        <a class="btn btn-danger btn-sm btn-manage" href="{% url 'syntaxexer-delete' quiz.id exer.id %}">Delete exercise</a>
        <!--button type="button"
                class="btn btn-warning btn-sm js-update-phono-quiz"
                data-url="{% url 'phonoquiz-update' quiz.id %}">
          Edit
        </button>
        &nbsp;
        <button type="button"
                class="btn btn-info btn-sm js-update-phono-exer"
                data-url="{% url 'phonoexer-list' quiz.id %}">
          Edit exercise
        </button>
        &nbsp;
        <button type="button"
                class="btn btn-danger btn-sm js-delete-phono-quiz"
                data-url="{% url 'phonoquiz-delete' quiz.id %}">
          Delete
        </button-->
      </td>
    </tr> 
    {% empty %}
    <tr>
      <td colspan="4" class="text-center bg-warning">No exercise</td>
    </tr>
    {% endfor %}

learnfrench/templates/learnfrench/teacherportal/includes/partial_syntaxquiz_list.html
  {% for quiz in syntaxquiz_list %}
    <tr>
      <td>{{ quiz.id }}</td>
      <td>{{ quiz.name }}</td>
      <td>
        <ul class="list-unstyled">
        {% for ex in quiz.syntaxexercise_set.all %}
        <li>{{ ex.name }}&nbsp; </li>
        {% endfor %}
        </ul>
      </td>
      <td>{{ quiz.description }}</td>
      <td>
        <a role="button"
           class="btn btn-warning btn-sm"
           href="{% url 'syntaxquiz-update' quiz.id %}">
          Edit
        </a>
        &nbsp;
        {% if quiz.syntaxexercise_set.all %}
        <a role="button"
                class="btn btn-info btn-sm js-update-phono-exer"
                href="{% url 'syntaxexer-list' quiz.id %}">
          Edit exercise
        </a>
        {% else %}
        <a role="button"
           class="btn btn-info btn-sm"
           href="{% url 'syntaxexer-create' quiz.id %}">
          Add exercise
        </a>
        {% endif %}
               &nbsp;
        <a role="button"
           class="btn btn-danger btn-sm"
           href="{% url 'syntaxquiz-delete' quiz.id %}">
          Delete
        </a>
      </td>
    </tr> 
    {% empty %}
    <tr>
      <td colspan="4" class="text-center bg-warning">No quiz</td>
    </tr>
    {% endfor %}